spring:
  datasource:
    url: jdbc:h2:file:./data/wholistika
    username: whol1st1ka-bak
    password: whol1st1k@.nta
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
frontend:
  url: http://localhost:5173
